module_label('character')
module_menu('   convert','modules/character/convert')
module_menu('   in out','modules/character/in%20out')
module_menu('   parse','modules/character/parse')
module_menu('   variable','modules/character/variable')
module_label('connect')
module_label('   svg')
module_menu('      ExtractFaces','modules/connect/svg/ExtractFaces')
module_menu('      PCB','modules/connect/svg/PCB')
module_menu('      SelectFace','modules/connect/svg/SelectFace')
module_label('convert')
module_label('   rgba')
module_menu('      jpg','modules/convert/rgba/jpg')
module_menu('      png','modules/convert/rgba/png')
module_label('   svg')
module_menu('      array','modules/convert/svg/array')
module_menu('      image','modules/convert/svg/image')
module_label('dev')
module_menu('   log','modules/dev/log')
module_label('event')
module_menu('   delay','modules/event/delay')
module_menu('   generate','modules/event/generate')
module_menu('   pause','modules/event/pause')
module_menu('   sequence','modules/event/sequence')
module_label('file')
module_menu('   save','modules/file/save')
module_label('frep')
module_label('   operators')
module_menu('      add','modules/frep/operators/add')
module_menu('      blend','modules/frep/operators/blend')
module_menu('      clearance','modules/frep/operators/clearance')
module_menu('      intersect','modules/frep/operators/intersect')
module_menu('      morph','modules/frep/operators/morph')
module_menu('      subtract','modules/frep/operators/subtract')
module_label('   shapes')
module_label('      2D')
module_menu('         arc','modules/frep/shapes/2D/arc')
module_menu('         circle','modules/frep/shapes/2D/circle')
module_menu('         function','modules/frep/shapes/2D/function')
module_menu('         involute gear','modules/frep/shapes/2D/involute%20gear')
module_menu('         involute rack','modules/frep/shapes/2D/involute%20rack')
module_menu('         polygon','modules/frep/shapes/2D/polygon')
module_menu('         rectangle','modules/frep/shapes/2D/rectangle')
module_menu('         right triangle','modules/frep/shapes/2D/right%20triangle')
module_menu('         triangle','modules/frep/shapes/2D/triangle')
module_label('      3D')
module_menu('         cone','modules/frep/shapes/3D/cone')
module_menu('         cube','modules/frep/shapes/3D/cube')
module_menu('         cylinder','modules/frep/shapes/3D/cylinder')
module_menu('         function','modules/frep/shapes/3D/function')
module_menu('         lattice','modules/frep/shapes/3D/lattice')
module_menu('         menger','modules/frep/shapes/3D/menger')
module_menu('         pyramid','modules/frep/shapes/3D/pyramid')
module_menu('         sphere','modules/frep/shapes/3D/sphere')
module_menu('         torus','modules/frep/shapes/3D/torus')
module_label('   transforms')
module_menu('      extrude','modules/frep/transforms/extrude')
module_menu('      inflate','modules/frep/transforms/inflate')
module_menu('      reflect','modules/frep/transforms/reflect')
module_menu('      repeat linear','modules/frep/transforms/repeat%20linear')
module_menu('      repeat rotary','modules/frep/transforms/repeat%20rotary')
module_menu('      revolve','modules/frep/transforms/revolve')
module_menu('      rotate','modules/frep/transforms/rotate')
module_menu('      scale','modules/frep/transforms/scale')
module_menu('      shear','modules/frep/transforms/shear')
module_menu('      shell','modules/frep/transforms/shell')
module_menu('      slice','modules/frep/transforms/slice')
module_menu('      taper','modules/frep/transforms/taper')
module_menu('      translate','modules/frep/transforms/translate')
module_label('   view')
module_menu('      render (CPU)','modules/frep/view/render%20(CPU)')
module_menu('      render (GPU)','modules/frep/view/render%20(GPU)')
module_menu('      slice','modules/frep/view/slice')
module_label('image')
module_menu('   boundingbox','modules/image/boundingbox')
module_menu('   color separation','modules/image/color%20separation')
module_menu('   distance transform','modules/image/distance%20transform')
module_menu('   dogbone','modules/image/dogbone')
module_menu('   edge detect','modules/image/edge%20detect')
module_menu('   function','modules/image/function')
module_menu('   motion detect','modules/image/motion%20detect')
module_menu('   offset','modules/image/offset')
module_menu('   orient edges','modules/image/orient%20edges')
module_menu('   palette','modules/image/palette')
module_menu('   raster mask','modules/image/raster%20mask')
module_menu('   size','modules/image/size')
module_menu('   threshold','modules/image/threshold')
module_menu('   vector mask','modules/image/vector%20mask')
module_menu('   vectorize','modules/image/vectorize')
module_label('input')
module_menu('   video','modules/input/video')
module_label('iterate')
module_menu('   step','modules/iterate/step')
module_menu('   step and delay','modules/iterate/step%20and%20delay')
module_label('library')
module_menu('   globals','modules/library/globals')
module_menu('   library','modules/library/library')
module_menu('   three.js','modules/library/three.js')
module_label('math')
module_menu('   benchmark','modules/math/benchmark')
module_menu('   dyadic','modules/math/dyadic')
module_menu('   glsl_benchmark','modules/math/glsl_benchmark')
module_menu('   parallel','modules/math/parallel')
module_menu('   scalar','modules/math/scalar')
module_label('mesh')
module_menu('   rotate','modules/mesh/rotate')
module_menu('   slice raster','modules/mesh/slice%20raster')
module_label('module')
module_menu('   create','modules/module/create')
module_menu('   delete','modules/module/delete')
module_menu('   move','modules/module/move')
module_label('network')
module_menu('   apa','modules/network/apa')
module_label('object')
module_menu('   construct','modules/object/construct')
module_menu('   download','modules/object/download')
module_menu('   set','modules/object/set')
module_menu('   string','modules/object/string')
module_menu('   view','modules/object/view')
module_label('path')
module_label('   formats')
module_menu('      dxf','modules/path/formats/dxf')
module_menu('      g-code','modules/path/formats/g-code')
module_menu('      svg','modules/path/formats/svg')
module_label('   machines')
module_label('      Roland')
module_label('         milling')
module_menu('            MDX-20','modules/path/machines/Roland/milling/MDX-20')
module_menu('            SRM-20','modules/path/machines/Roland/milling/SRM-20')
module_label('         vinyl cutter')
module_menu('            GX-24','modules/path/machines/Roland/vinyl%20cutter/GX-24')
module_menu('      ShopBot','modules/path/machines/ShopBot')
module_label('      laser cutter')
module_menu('         Epilog','modules/path/machines/laser%20cutter/Epilog')
module_menu('   view','modules/path/view')
module_label('processes')
module_label('   cut')
module_menu('      raster','modules/processes/cut/raster')
module_label('   mill')
module_label('      raster')
module_menu('         2.5D','modules/processes/mill/raster/2.5D')
module_menu('         2D','modules/processes/mill/raster/2D')
module_label('read')
module_menu('   png','modules/read/png')
module_menu('   stl','modules/read/stl')
module_menu('   svg','modules/read/svg')
module_menu('   text','modules/read/text')
module_label('socket')
module_label('   server')
module_menu('      device','modules/socket/server/device')
module_menu('      echo','modules/socket/server/echo')
module_menu('      print','modules/socket/server/print')
module_menu('      serial','modules/socket/server/serial')
module_menu('      udp','modules/socket/server/udp')
module_menu('   websocket','modules/socket/websocket')
module_label('string')
module_menu('   format','modules/string/format')
module_menu('   variables','modules/string/variables')
module_label('ui')
module_menu('   bar graph','modules/ui/bar%20graph')
module_menu('   button window','modules/ui/button%20window')
module_menu('   color','modules/ui/color')
module_menu('   label','modules/ui/label')
module_menu('   slider','modules/ui/slider')
module_menu('   text window','modules/ui/text%20window')

