program_label('frep')
program_menu('   gears','programs/frep/gears')
program_menu('   lattice torus','programs/frep/lattice%20torus')
program_menu('   smiley','programs/frep/smiley')
program_label('image')
program_menu('   function','programs/image/function')
program_menu('   motion detect','programs/image/motion%20detect')
program_menu('   palette mask raster','programs/image/palette%20mask%20raster')
program_menu('   palette mask vector','programs/image/palette%20mask%20vector')
program_menu('   vectorize','programs/image/vectorize')
program_label('iterate')
program_menu('   z theta scan','programs/iterate/z%20theta%20scan')
program_label('machines')
program_label('   Epilog')
program_menu('      cut png','programs/machines/Epilog/cut%20png')
program_menu('      cut svg','programs/machines/Epilog/cut%20svg')
program_menu('      cut svg connect','programs/machines/Epilog/cut%20svg%20connect')
program_label('   G-code')
program_menu('      mill 2D png','programs/machines/G-code/mill%202D%20png')
program_menu('      mill 2D svg','programs/machines/G-code/mill%202D%20svg')
program_label('   Roland')
program_label('      mill')
program_label('         MDX-20')
program_menu('            PCB','programs/machines/Roland/mill/MDX-20/PCB')
program_menu('            PCB png','programs/machines/Roland/mill/MDX-20/PCB%20png')
program_menu('            PCB svg','programs/machines/Roland/mill/MDX-20/PCB%20svg')
program_label('         SRM-20')
program_menu('            PCB png','programs/machines/Roland/mill/SRM-20/PCB%20png')
program_menu('            PCB svg','programs/machines/Roland/mill/SRM-20/PCB%20svg')
program_menu('            PCB svg connect','programs/machines/Roland/mill/SRM-20/PCB%20svg%20connect')
program_label('      vinyl cutter')
program_label('         GX-24')
program_menu('            cut png','programs/machines/Roland/vinyl%20cutter/GX-24/cut%20png')
program_menu('            cut svg','programs/machines/Roland/vinyl%20cutter/GX-24/cut%20svg')
program_menu('            cut svg connect','programs/machines/Roland/vinyl%20cutter/GX-24/cut%20svg%20connect')
program_label('   ShopBot')
program_menu('      mill 2D png','programs/machines/ShopBot/mill%202D%20png')
program_menu('      mill 2D png PCB','programs/machines/ShopBot/mill%202D%20png%20PCB')
program_menu('      mill 2D stl','programs/machines/ShopBot/mill%202D%20stl')
program_menu('      mill 2D svg','programs/machines/ShopBot/mill%202D%20svg')
program_menu('      mill 2D svg connect','programs/machines/ShopBot/mill%202D%20svg%20connect')
program_label('math')
program_menu('   benchmark','programs/math/benchmark')
program_menu('   expressions','programs/math/expressions')
program_label('processes')
program_label('   cut')
program_label('      raster')
program_menu('         video','programs/processes/cut/raster/video')
program_label('   mill')
program_label('      raster')
program_menu('         2.5D','programs/processes/mill/raster/2.5D')
program_menu('         2D','programs/processes/mill/raster/2D')
program_label('variable')
program_menu('   text variables','programs/variable/text%20variables')

